export const SET_TABLE_DATA = 'SET-TABLE-DATA';
export const CHANGE_TABLE_ITEM = 'CHANGE-TABLE-ITEM';
export const IS_FETCHING = 'IS-FETCHING';
export const CHANGE_VALUE = 'CHANGE-VALUE';
export const SET_INTERVAL = 'SET-INTERVAL';
export const INTERVAL_COUNT_CHANGE = 'INTERVAL-COUNT-CHANGE';